version: '3.8'

services:
  # QR API Application (Rust)
  qr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-api-rust
    ports:
      - "8080:8080"
    environment:
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_demo_key}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_demo_secret}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:///app/data/qrapi.db
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - DOMAIN=${DOMAIN:-localhost:8080}
      - PORT=8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - qr-network
    mem_limit: 200m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: qr-redis
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - qr-network
    mem_limit: 70m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  qr-network:
    driver: bridge