version: '3.8'

services:
  qr-api:
    image: python:3.11-slim
    container_name: qr-api-simple
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    environment:
      - BASE_URL=http://localhost:5000
      - PORT=5000
    volumes:
      - .:/app
      - ./data:/app/data
    restart: unless-stopped